[package]
name = "rmk-corne"
version = "0.0.1"
authors = ["LegitCamper <sawyerbristol@gmail.com>"]
description = "Keyboard firmware written in Rust"
edition = "2024"

[features]
default = ["central"]
central = [
  "dep:embassy-nrf",
  "dep:nrf-sdc",
  "dep:nrf-mpsl",
  "rmk/nrf52840_ble",
  "rmk/adafruit_bl",
  "embassy-time/tick-hz-32_768",
  "embassy-time/defmt-timestamp-uptime",
]
peripheral_left = [
  "dep:embassy-nrf",
  "dep:nrf-sdc",
  "dep:nrf-mpsl",
  "rmk/nrf52840_ble",
  "rmk/adafruit_bl",
  "embassy-time/tick-hz-32_768",
  "embassy-time/defmt-timestamp-uptime",
]
peripheral_right = [
  "dep:embassy-nrf",
  "dep:nrf-sdc",
  "dep:nrf-mpsl",
  "rmk/nrf52840_ble",
  "rmk/adafruit_bl",
  "embassy-time/tick-hz-32_768",
  "embassy-time/defmt-timestamp-uptime",
]
reset = []
usb_logging = ["rmk/usb_log"]

[[bin]]
name = "central"
path = "src/central.rs"
required-features = ["central"]

[[bin]]
name = "peripheral_left"
path = "src/peripherals.rs"
required-features = ["peripheral_left"]

[[bin]]
name = "peripheral_right"
path = "src/peripherals.rs"
required-features = ["peripheral_right"]

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"

[dependencies]
rmk = { git = "https://github.com/HaoboGu/rmk/", rev = "1a411da55bcaae80487ce76ca00351ef1aee32f5", features = [
  "split",
  "storage",
  "async_matrix",
  "rynk",
  "watchdog",
], default-features = false }

# nRF52840 (XIAO BLE peripherals) only
embassy-nrf = { version = "0.11", features = [
  "defmt",
  "nrf52840",
  "time-driver-rtc1",
  "gpiote",
  "unstable-pac",
  "nfc-pins-as-gpio",
  "time",
], optional = true }
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc", rev = "abe49d22ebfc85fae134eb082fbfddf752016a55", features = [
  "defmt",
  "peripheral",
  "central",
  "nrf52840",
], optional = true }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc", rev = "abe49d22ebfc85fae134eb082fbfddf752016a55", features = [
  "defmt",
  "critical-section-impl",
  "nrf52840",
], optional = true }

bt-hci = { version = "0.9", features = ["defmt"] }

cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
portable-atomic = { version = "1", features = ["critical-section"] }
embassy-time = { version = "0.5", features = ["defmt"] }
embassy-executor = { version = "0.10", features = [
  "defmt",
  "platform-cortex-m",
  "executor-thread",
] }
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
static_cell = "2"

