[env]
RMK_RESET_ARG = { script = [
  "if [ -n \"$RMK_RESET\" ]; then echo \"reset\"; fi",
] }
RMK_LOG_ARG = { script = [
  "if [ -n \"$RMK_LOG\" ]; then echo \"usb_logging\"; fi",
] }
RUST_VER = "1.89.0"

[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = [
  "-h",
] }

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "+${RUST_VER}",
  "objcopy",
  "--release",
  "--bin",
  "central",
  "--no-default-features",
  "--features",
  "central,ble,${RMK_RESET_ARG},${RMK_LOG_ARG}",
  "--",
  "-O",
  "ihex",
  "rmk-central.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral-left]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "+${RUST_VER}",
  "objcopy",
  "--release",
  "--bin",
  "peripheral_left",
  "--no-default-features",
  "--features",
  "peripheral_left,ble,${RMK_RESET_ARG}",
  "--",
  "-O",
  "ihex",
  "rmk-peripheral-left.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral-right]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "+${RUST_VER}",
  "objcopy",
  "--release",
  "--bin",
  "peripheral_right",
  "--no-default-features",
  "--features",
  "peripheral_right,ble,${RMK_RESET_ARG}",
  "--",
  "-O",
  "ihex",
  "rmk-peripheral-right.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-wired-left]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "+${RUST_VER}",
  "objcopy",
  "--release",
  "--bin",
  "peripheral_left",
  "--no-default-features",
  "--features",
  "peripheral_left,wired,${RMK_RESET_ARG}",
  "--",
  "-O",
  "ihex",
  "rmk-wired-left.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-wired-right]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "+${RUST_VER}",
  "objcopy",
  "--release",
  "--bin",
  "peripheral_right",
  "--no-default-features",
  "--features",
  "peripheral_right,wired,${RMK_RESET_ARG}",
  "--",
  "-O",
  "ihex",
  "rmk-wired-right.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "rmk-central.hex",
  "--output-path",
  "rmk-central.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral-left]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "rmk-peripheral-left.hex",
  "--output-path",
  "rmk-peripheral-left.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-peripheral-left"]

[tasks.uf2-peripheral-right]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "rmk-peripheral-right.hex",
  "--output-path",
  "rmk-peripheral-right.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-peripheral-right"]

[tasks.uf2-wired-left]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "rmk-wired-left.hex",
  "--output-path",
  "rmk-wired-left.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-wired-left"]

[tasks.uf2-wired-right]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "rmk-wired-right.hex",
  "--output-path",
  "rmk-wired-right.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-wired-right"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral-left", "uf2-peripheral-right"]

# Fully wired build: no BLE dongle. Flash rmk-wired-left.uf2 to the half that
# plugs into USB, and rmk-wired-right.uf2 to the other half.
[tasks.uf2-wired]
dependencies = ["uf2-wired-left", "uf2-wired-right"]
