# XIAO BLE nRF52840 (central + peripherals)
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip nRF52840_xxAA"
linker = "flip-link"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
